version: '3.3'
services:
  vollmed_db:
    platform: linux/x86_64 # So para o caso de estar com Mac M alguma coisa
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'vollmed_api'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'do_not_change_it'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
