spring:
  datasource:
    url: jdbc:h2:mem:vollmed_api
    username: sa
    password:
# Enables H2 Console
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true