spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: admin
    password: do_not_change_it

server:
  error:
    include-stacktrace: never
#To change the name of the pageable parameters
#  data:
#    web:
#      pageable:
#        page-parameter: pagina
#        size-parameter: tamanho
#      sort:
#        sort-parameter: ordem
