spring:
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: never
  jpa:
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: admin
    password: do_not_change_it
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    static-path-pattern: /swagger*:api
api:
  security:
    token:
      secret: ${JWT_SECRET:donotchangeit}

server:
  error:
    include-stacktrace: never

#Muda o nome dos parametros do pageable
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem
