spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: admin
    password: do_not_change_it

server:
  error:
    include-stacktrace: never
#To change the name of the pageable parameters
#  data:
#    web:
#      pageable:
#        page-parameter: pagina
#        size-parameter: tamanho
#      sort:
#        sort-parameter: ordem

# Run application with memory database instead of "physical one"
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:vollmed_api
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:vollmed_api
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
          format_sql: true